MAT-126 Shipping Responsive
Skyrin/client-materialbank-checkout pull request #48
Opened 2021-02-11 15:37 UTC by ioanaconstantinescu

- search bar should be fixed once MAT-125, which includes header styling, will be merged.

2021-02-16 10:34 UTC, RaduDurican requested changes

2021-02-16 10:34 UTC, RaduDurican commented on src/components/common/SearchBar/SearchBar.module.scss
Let's make the search bar extend the full width for mobile :D
https://gyazo.com/2b351fc8992b5648c97986dc7c8a51a5

2021-02-16 10:34 UTC, RaduDurican commented on src/components/common/Forms/MapAddressForm/MapAddressForm.module.scss
> +        margin-top: 10px;
Looks a bit uneven :(
https://gyazo.com/39618438a57d0cbf8a6f487f92647a57

2021-02-16 14:01 UTC, ioanaconstantinescu commented
Solved comments

2021-02-18 09:53 UTC, RaduDurican approved these changes

2021-02-18 09:58 UTC, merged